export const TOGGLE_LAYER = 'TOGGLE_LAYER'
export const ADD_LAYER = 'ADD_LAYER'
export const GET_DBC_LAYERS_REQUEST = 'GET_DBC_LAYERS_REQUEST'
export const GET_DBC_LAYERS_SUCCESS = 'GET_DBC_LAYERS_SUCCESS'