export const TOGGLE_LAYER = 'TOGGLE_LAYER'
export const TOGGLE_LAYER_MODE = 'TOGGLE_LAYER_MODE'

export const REQUEST_LAYER_VECTOR = 'REQUEST_LAYER_VECTOR'
export const LAYER_VECTOR_SUCCESS = 'ADD_LAYER_VECTOR'

export const REQUEST_CACHE_OFFLINE_MAP = 'REQUEST_CACHE_OFFLINE_MAP'
export const CACHE_OFFLINE_MAP_SUCCESS = 'CACHE_OFFLINE_MAP_SUCCESS'

export const REQUEST_CACHE_LAYER = 'REQUEST_CACHE_LAYER'
export const CACHE_LAYER_SUCCESS = 'CACHE_LAYER_SUCCESS'

export const ADD_LAYER = 'ADD_LAYER'

export const GET_DBC_LAYERS_REQUEST = 'GET_DBC_LAYERS_REQUEST'
export const GET_DBC_LAYERS_SUCCESS = 'GET_DBC_LAYERS_SUCCESS'

export const PROMPT_FOR_SHAPE_REQUEST = 'PROMPT_FOR_SHAPE_REQUEST'
export const PROMPT_FOR_SHAPE_SUCCESS = 'PROMPT_FOR_SHAPE_SUCCESS'