[tool.poetry]
name = "api"
version = "0.1.0"
description = ""
authors = ["Micheal Wells <micheal.w.wells@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.112.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
